import MEESHO_WESTERN_PRODUCTS from './meesho-products.json';
import MEESHO_DRESS_PRODUCTS from './meesho-dresses.json';
import MEESHO_PRICE_OVERRIDES from './meesho-price-overrides.json';

export const MEESHO_CREATOR_LINK = 'https://www.meesho.com/af_invite/374453404:youtube_long_form:12492338?p_id=542355935&ext_id=8ywkin&utm_source=youtube_long_form';

export const STORES = ['Amazon', 'Flipkart', 'Myntra', 'Meesho', 'Pinterest'];

export const STORE_CONFIG = {
  Amazon: { color: '#e87922', pale: '#fff1e6', site: 'amazon.in' },
  Flipkart: { color: '#2877e8', pale: '#eaf2ff', site: 'flipkart.com' },
  Myntra: { color: '#ee4a73', pale: '#fff0f4', site: 'myntra.com' },
  Meesho: { color: '#a348a2', pale: '#f9eefa', site: 'meesho.com' },
  Pinterest: { color: '#e60023', pale: '#ffe6e9', site: 'pinterest.com' },
};

export const INITIAL_COLLECTIONS = [
  {
    id: 'spider-chrome-vault',
    title: 'Spider Web & Y2K Chrome Vault',
    subtitle: 'Silver ruby pendants, liquid chrome cases & futuristic tech accessories',
    category: 'Accessories',
    coverImages: [
      '/images/meesho-earrings-combo.webp',
      '/images/meesho-flower-earrings.webp',
      '/images/gold-hoops.jpg',
    ],
    tint: 'lilac',
  },
  {
    id: 'brasilcore-edits',
    title: 'Brasilcore & Y2K Baby Tees',
    subtitle: 'Viral Pinterest yellow halter tops, baby tees & leopard corsets',
    category: 'Tops & Tunics',
    coverImages: [
      '/images/meesho-yellow-side-dori-top.webp',
      '/images/meesho-red-checked-crop-top.webp',
      '/images/meesho-plaid-bow-peplum-top.webp',
    ],
    tint: 'butter',
  },
  {
    id: 'pinterest-streetwear',
    title: 'Pinterest Racing & Streetwear',
    subtitle: 'Vintage Ferrari F1 bombers, Spider-Man tees & oversized fits',
    category: 'Tops & Tunics',
    coverImages: [
      '/images/meesho-western-party-top.webp',
      '/images/meesho-black-cardigan.webp',
      '/images/meesho-hot-pink-puffer.webp',
    ],
    tint: 'peach',
  },
  {
    id: 'blokecore-jerseys',
    title: 'Viral Blokecore & Jerseys',
    subtitle: 'Oversized football kits, retro Brazil & Madrid edits',
    category: 'Tops & Tunics',
    coverImages: [
      '/images/meesho-western-square-print-top.webp',
      '/images/meesho-side-dori-main.webp',
      '/images/meesho-checked-peplum-top.webp',
    ],
    tint: 'butter',
  },
  {
    id: 'meesho-western-2026',
    title: 'Topwear, on repeat',
    subtitle: 'Dori details, cute crops & everyday layers',
    category: 'Tops & Tunics',
    coverImages: ['/images/meesho-side-dori-main.webp', '/images/meesho-western-square-print-top.webp', '/images/meesho-plaid-bow-peplum-top.webp'],
    tint: 'peach',
  },
  {
    id: 'meesho-kurtis-2026',
    title: 'Kurtis, but make it cool',
    subtitle: 'Printed kurtis & easy tunic tops',
    category: 'Kurtis',
    coverImages: ['/images/meesho-peach-short-kurti.webp', '/images/meesho-peach-embroidered-tunic.webp', '/images/meesho-kurti-dailywear-hgyhrb.webp'],
    tint: 'lilac',
  },
  {
    id: 'meesho-dresses-2026',
    title: 'Dress like the main character',
    subtitle: 'Soft florals, bodycon moments & after-dark sparkle',
    category: 'Women Dresses',
    coverImages: ['/images/meesho-dress-ae6lv9.webp', '/images/meesho-dress-gpc4vn.webp', '/images/meesho-dress-ibsnwj.webp'],
    tint: 'peach',
  },
  {
    id: 'winter-2026',
    title: 'Cold-girl era',
    subtitle: 'Puffers, soft knits & statement layers',
    category: 'Winter',
    coverImages: ['/images/meesho-hot-pink-puffer.webp', '/images/meesho-puffer-vest.webp', '/images/meesho-kashmiri-shawl.webp'],
    tint: 'blue',
  },
  {
    id: 'everyday-style',
    title: 'Everyday, reimagined',
    subtitle: 'Easy pieces I keep reaching for',
    category: 'Style',
    coverImages: ['/images/meesho-kurti-set.webp', '/images/meesho-canvas-tote.webp', '/images/canvas-sneakers.jpg'],
    tint: 'sage',
  },
  {
    id: 'slow-mornings',
    title: 'Slow morning club',
    subtitle: 'Little rituals, softer starts',
    category: 'Beauty',
    coverImages: ['/images/face-serum.jpg', '/images/meesho-earrings-combo.webp', '/images/ceramic-vases.jpg'],
    tint: 'peach',
  },
  {
    id: 'home-softly',
    title: 'Home, but softer',
    subtitle: 'Small details that change a room',
    category: 'Home',
    coverImages: ['/images/meesho-jute-lamp.webp', '/images/ceramic-vases.jpg', '/images/face-serum.jpg'],
    tint: 'lilac',
  },
  {
    id: 'under-999',
    title: 'Cute finds under ₹999',
    subtitle: 'A little treat, not a splurge',
    category: 'Under ₹999',
    coverImages: ['/images/meesho-earrings-combo.webp', '/images/meesho-canvas-tote.webp', '/images/ceramic-vases.jpg'],
    tint: 'butter',
  },
];

const BASE_PRODUCTS = [
  {
    id: 'p-linen',
    title: 'The linen day set',
    subtitle: 'Soft, easy, goes with everything',
    brand: 'House of Chic',
    store: 'Myntra',
    category: 'Fashion',
    collectionId: 'everyday-style',
    image: '/images/linen-set.jpg',
    imagePosition: '50% 42%',
    imageFit: 'cover',
    tint: 'sage',
    price: 1499,
    oldPrice: 2299,
    clicks: 842,
    commission: '8% est.',
    saved: false,
    affiliateUrl: '',
  },
  {
    id: 'p-meesho-tote',
    title: 'Canvas tote with a happy print',
    subtitle: 'Cream printed carryall · 1 compartment',
    brand: 'Meesho product listing',
    store: 'Meesho',
    category: 'Fashion',
    collectionId: 'everyday-style',
    image: '/images/meesho-canvas-tote.webp',
    imagePosition: '50% 39%',
    imageFit: 'cover',
    tint: 'butter',
    price: 270,
    oldPrice: null,
    clicks: 0,
    commission: '',
    saved: true,
    affiliateUrl: '',
    productUrl: 'https://www.meesho.com/tote-bags-for-women-girls-canvas-cute-tote-bags-fashion-bag-for-college-office/p/6t8k9b',
    isRealListing: true,
    priceCheckedAt: '2026-10-03',
  },
  {
    id: 'p-winter-pink-puffer',
    title: 'Hot-pink cropped puffer jacket',
    subtitle: 'Lightweight warmth · statement color',
    brand: 'Meesho product listing',
    store: 'Meesho',
    category: 'Winter',
    collectionId: 'winter-2026',
    image: '/images/meesho-hot-pink-puffer.webp',
    imagePosition: '50% 34%',
    imageFit: 'cover',
    tint: 'peach',
    price: 412,
    oldPrice: null,
    clicks: 0,
    commission: '',
    saved: false,
    affiliateUrl: '',
    productUrl: 'https://www.meesho.com/hot-pink-puffer-jacket-for-women/p/7ubl63',
    isRealListing: true,
    seasonalTag: 'WINTER',
    priceCheckedAt: '2026-10-03',
  },
  {
    id: 'p-serum',
    title: 'The daily glow serum',
    subtitle: 'A lightweight little reset',
    brand: 'Desert Flower',
    store: 'Amazon',
    category: 'Beauty',
    collectionId: 'slow-mornings',
    image: '/images/face-serum.jpg',
    imagePosition: '50% 50%',
    imageFit: 'cover',
    tint: 'peach',
    price: 579,
    oldPrice: 799,
    clicks: 512,
    commission: '5% est.',
    saved: false,
    affiliateUrl: '',
  },
  {
    id: 'p-sneakers',
    title: 'Cloud-walk canvas sneakers',
    subtitle: 'Comfy enough for the long way home',
    brand: 'Walk the Talk',
    store: 'Flipkart',
    category: 'Fashion',
    collectionId: 'everyday-style',
    image: '/images/canvas-sneakers.jpg',
    imagePosition: '50% 54%',
    imageFit: 'cover',
    tint: 'blue',
    price: 1199,
    oldPrice: 1599,
    clicks: 487,
    commission: '6% est.',
    saved: false,
    affiliateUrl: '',
  },
  {
    id: 'p-meesho-earrings',
    title: '10-pair everyday earrings edit',
    subtitle: 'Everyday mix · 10 pairs',
    brand: 'Meesho product listing',
    store: 'Meesho',
    category: 'Accessories',
    collectionId: 'under-999',
    image: '/images/meesho-earrings-combo.webp',
    imagePosition: '50% 38%',
    imageFit: 'cover',
    tint: 'butter',
    price: 155,
    oldPrice: null,
    clicks: 0,
    commission: '',
    saved: false,
    affiliateUrl: '',
    productUrl: 'https://www.meesho.com/small-earrings-pair-of-10-combo/p/5xcd6h',
    isRealListing: true,
    rating: 3.9,
    ratingCount: 1149,
    priceCheckedAt: '2026-10-03',
  },
  {
    id: 'p-vases',
    title: 'Sculptural ceramic vases',
    subtitle: 'Instant coffee-table energy',
    brand: 'Home Fables',
    store: 'Amazon',
    category: 'Home',
    collectionId: 'home-softly',
    image: '/images/ceramic-vases.jpg',
    imagePosition: '50% 52%',
    imageFit: 'cover',
    tint: 'lilac',
    price: 849,
    oldPrice: 1199,
    clicks: 396,
    commission: '5% est.',
    saved: false,
    affiliateUrl: '',
  },
  {
    id: 'p-meesho-kurti',
    title: 'Vidusha blue-print cotton kurti set',
    subtitle: 'Printed 3-piece set · three-quarter sleeves',
    brand: 'Vidusha',
    store: 'Meesho',
    category: 'Kurtis',
    collectionId: 'meesho-kurtis-2026',
    image: '/images/meesho-kurti-set.webp',
    imagePosition: '50% 35%',
    imageFit: 'cover',
    tint: 'blue',
    price: 478,
    pricePrefix: 'From',
    oldPrice: null,
    clicks: 0,
    commission: '',
    saved: false,
    affiliateUrl: '',
    productUrl: 'https://www.meesho.com/vidusha-printed-soft-cotton-kurti-set-for-womens/p/7ql4tg',
    isRealListing: true,
    rating: 4.1,
    priceCheckedAt: '2026-10-03',
  },
  {
    id: 'p-meesho-lamp',
    title: 'Antique table lamp with jute shade',
    subtitle: 'Woven natural shade · warm bedside glow',
    brand: 'Meesho product listing',
    store: 'Meesho',
    category: 'Home',
    collectionId: 'home-softly',
    image: '/images/meesho-jute-lamp.webp',
    imagePosition: '50% 38%',
    imageFit: 'cover',
    tint: 'sage',
    price: 796,
    oldPrice: null,
    clicks: 0,
    commission: '',
    saved: false,
    affiliateUrl: '',
    productUrl: 'https://www.meesho.com/antique-table-lamp-with-jute-shade/p/7gk5gy',
    isRealListing: true,
    priceCheckedAt: '2026-10-03',
  },
  {
    id: 'p-winter-cardigan',
    title: 'Black v-neck wool-blend cardigan',
    subtitle: 'Soft knit · button-front layering piece',
    brand: 'Meesho product listing',
    store: 'Meesho',
    category: 'Winter',
    collectionId: 'winter-2026',
    image: '/images/meesho-black-cardigan.webp',
    imagePosition: '50% 39%',
    imageFit: 'cover',
    tint: 'sage',
    price: 207,
    oldPrice: null,
    clicks: 0,
    commission: '',
    saved: false,
    affiliateUrl: '',
    productUrl: 'https://www.meesho.com/premium-black-wool-blend-winter-cardigansweater-for-women/p/a9tn1w',
    isRealListing: true,
    seasonalTag: 'WINTER',
    rating: 3.8,
    ratingCount: 38,
    priceCheckedAt: '2026-10-03',
  },
  {
    id: 'p-winter-shawl',
    title: 'Kashmiri-feel embroidered wool stole',
    subtitle: 'Floral jaal embroidery · 2 m wrap',
    brand: 'Meesho product listing',
    store: 'Meesho',
    category: 'Winter',
    collectionId: 'winter-2026',
    image: '/images/meesho-kashmiri-shawl.webp',
    imagePosition: '50% 46%',
    imageFit: 'cover',
    tint: 'butter',
    price: 274,
    oldPrice: 303,
    clicks: 0,
    commission: '',
    saved: false,
    affiliateUrl: '',
    productUrl: 'https://www.meesho.com/kashmiri-shawl-stole-for-women-pashmina-feel-woolen-embroidery-jaal-shawls-for-winter-28-x-80-inches-wraps/p/3b6toh',
    isRealListing: true,
    seasonalTag: 'WINTER',
    rating: 3.9,
    ratingCount: 503,
    priceCheckedAt: '2026-10-03',
  },
  {
    id: 'p-winter-vest',
    title: 'Quilted puffer vest',
    subtitle: 'Sleeveless layer · easy over knits',
    brand: 'Meesho product listing',
    store: 'Meesho',
    category: 'Winter',
    collectionId: 'winter-2026',
    image: '/images/meesho-puffer-vest.webp',
    imagePosition: '50% 38%',
    imageFit: 'cover',
    tint: 'butter',
    price: 439,
    pricePrefix: 'From',
    oldPrice: null,
    clicks: 0,
    commission: '',
    saved: false,
    affiliateUrl: '',
    productUrl: 'https://www.meesho.com/trendy-puffer-vest-jacket-for-women-stylish-cozy-winter-wear/p/7kphk7',
    isRealListing: true,
    seasonalTag: 'WINTER',
    rating: 4.0,
    ratingCount: 84,
    priceCheckedAt: '2026-10-03',
  },
];

function applyMeeshoPriceOverride(product) {
  if (product.store !== 'Meesho' || !product.productUrl) return product;
  let extId = '';
  try {
    const url = new URL(product.productUrl);
    extId = url.searchParams.get('ext_id') || '';
    if (!extId) {
      const segments = url.pathname.split('/').filter(Boolean);
      if (segments.length >= 3 && segments[0].toLowerCase() === 's' && segments[1].toLowerCase() === 'p') extId = segments[2];
      if (!extId && segments.length >= 2 && segments[segments.length - 2].toLowerCase() === 'p') extId = segments[segments.length - 1];
    }
  } catch { /* non-absolute sample URLs do not get a price override */ }
  const override = extId ? MEESHO_PRICE_OVERRIDES[extId.toLowerCase()] : null;
  if (!override) return product;
  return {
    ...product,
    price: override.price,
    oldPrice: override.oldPrice ?? null,
    priceCheckedAt: override.priceCheckedAt || product.priceCheckedAt,
    affiliateUrl: override.affiliateUrl || product.affiliateUrl || '',
    category: override.category || product.category,
    subtitle: override.subtitle || product.subtitle,
    priceSyncManaged: true,
  };
}

const CURATED_LISTING_GALLERIES = {
  // Split the two real product views already present in each supplied Meesho collage.
  // Opposite starting frames keep these near-identical source listings visually distinct.
  'p-meesho-printed-side-dori-top': {
    galleryImages: ['/images/meesho-side-dori-main-view-front.webp', '/images/meesho-side-dori-main-view-side.webp'],
    galleryUseAsPrimary: true,
    galleryImageFit: 'contain',
  },
  'p-meesho-dailywear-kurti-hgyjn7': {
    galleryImages: ['/images/meesho-kurti-dailywear-hgyjn7-view-side.webp', '/images/meesho-kurti-dailywear-hgyjn7-view-front.webp'],
    galleryUseAsPrimary: true,
    galleryImageFit: 'contain',
  },
};

export const INITIAL_PRODUCTS = [...BASE_PRODUCTS, ...MEESHO_WESTERN_PRODUCTS, ...MEESHO_DRESS_PRODUCTS].map((product) => ({
  ...applyMeeshoPriceOverride(product),
  ...(CURATED_LISTING_GALLERIES[product.id] || {}),
}));

export function detectStore(url = '') {
  const value = url.toLowerCase();
  if (value.includes('meesho.com')) return 'Meesho';
  if (value.includes('amazon.') || value.includes('amzn.to')) return 'Amazon';
  if (value.includes('flipkart.com') || value.includes('fkrt.it')) return 'Flipkart';
  if (value.includes('myntra.com') || value.includes('myntr.in')) return 'Myntra';
  if (value.includes('pinterest.') || value.includes('pin.it') || value.includes('pinimg.com')) return 'Pinterest';
  return '';
}

export function storeSearchUrl(store, query) {
  const q = encodeURIComponent(query || 'popular picks');
  if (store === 'Amazon') return `https://www.amazon.in/s?k=${q}`;
  if (store === 'Flipkart') return `https://www.flipkart.com/search?q=${q}`;
  if (store === 'Myntra') return `https://www.myntra.com/${q}`;
  if (store === 'Meesho') return `https://www.meesho.com/search?q=${q}`;
  if (store === 'Pinterest') return `https://www.pinterest.com/search/pins/?q=${q}`;
  return 'https://www.meesho.com';
}
